### ISSUE TITLE
请教一下大佬图标代码是在哪里找的。

### ISSUE THREAD

**Issue by BlackKongo** [vaemc/WpfTimQQ#1]
![image](https://user-images.githubusercontent.com/44402336/204463169-5e8aa829-21ff-476e-b835-cdd5fd5927e0.png)
就像这种。

**Comment by vaemc** [comment]
这儿 [https://materialdesignicons.com/](https://materialdesignicons.com/)
![image](https://user-images.githubusercontent.com/16460137/206762632-85641b11-25d5-4986-a3b4-c02c5eedcf31.png)
